export const UI_TEXT = {
  appName: 'Highlight Translate',
  trigger: '译',
  detectingLanguage: '正在检测语言…',
  translationDialogLabel: '翻译结果',
  closeTranslationLabel: '关闭翻译卡片',
  retry: '重试',
  openSettings: '前往设置',
  copy: '复制',
  copied: '已复制',
  copyFailed: '复制失败，请重试。',
  translating: '正在翻译…',
  incompleteTranslation: '翻译未完成',
  unableToTranslate: '无法翻译',
  chinese: '中文',
  autoDetect: '自动检测',
  targetLanguage: '简体中文',
  languageArabic: '阿拉伯语',
  languageGerman: '德语',
  languageEnglish: '英语',
  languageSpanish: '西班牙语',
  languageFrench: '法语',
  languageHindi: '印地语',
  languageItalian: '意大利语',
  languageJapanese: '日语',
  languageKorean: '韩语',
  languagePortuguese: '葡萄牙语',
  languageRussian: '俄语',
  optionsPageTitle: 'Highlight Translate 设置',
  optionsHeading: '设置 DeepSeek API Key',
  optionsIntro: 'Key 只保存在本机扩展存储中，由扩展后台在请求时使用。',
  apiKeyLabel: 'API Key',
  apiKeyPlaceholder: '输入 DeepSeek API Key',
  show: '显示',
  hide: '隐藏',
  save: '保存',
  clear: '清除',
  testConnection: '测试连接',
  optionsNote: '保存不会自动测试连接；测试结果也不会修改已保存的 Key。',
  keyLoaded: '已加载本机保存的 API Key。',
  keySaved: 'API Key 已保存。',
  keyCleared: 'API Key 已清除。',
  keySaveFailed: '保存失败，请重试。',
  keyClearFailed: '清除失败，请重试。',
  enterKeyBeforeTest: '请输入 API Key 后再测试。',
  testingConnection: '正在测试连接…',
  connectionSucceeded: '连接成功。',
  connectionFailed: '连接测试失败，请重试。',
  settingsReadFailed: '读取本机设置失败，请刷新页面重试。',
} as const;

export type UiTextKey = keyof typeof UI_TEXT;
